# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-27 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mbbapp', '0003_auto_20181027_0816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passwrd',
            new_name='password',
        ),
    ]
