# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-29 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbbapp', '0006_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='num',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
