# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-30 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbbapp', '0010_goods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=50)),
                ('mbbprice', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=20)),
                ('heading', models.CharField(max_length=255)),
                ('picnum', models.CharField(max_length=255)),
                ('pic1', models.CharField(max_length=255)),
                ('pic2', models.CharField(max_length=255)),
                ('pic3', models.CharField(max_length=255)),
                ('pic4', models.CharField(max_length=255)),
                ('pic5', models.CharField(max_length=255)),
                ('pic6', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='goods',
            name='pic2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='pic3',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
