# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-31 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbbapp', '0012_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default='/static/img/index/head.jpeg', max_length=256),
        ),
    ]
