# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-31 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbbapp', '0013_auto_20181031_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
