# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-06 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbbapp', '0014_auto_20181031_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usercart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('goodnum', models.CharField(max_length=200)),
                ('num', models.CharField(max_length=200)),
                ('isselect', models.BooleanField(default=True)),
            ],
        ),
    ]
