# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-06 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mbbapp', '0017_auto_20181106_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbbapp.User'),
        ),
    ]
