# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-06 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbbapp', '0019_auto_20181106_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='num',
            field=models.IntegerField(),
        ),
    ]
