# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-12 01:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mbbapp', '0020_auto_20181106_0812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernum', models.CharField(max_length=255)),
                ('adv', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbbapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=255)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbbapp.Detail')),
                ('ordernum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbbapp.Order')),
            ],
        ),
    ]
